#!/bin/bash

git fetch upstream
git checkout upstream/main -- apache
git checkout upstream/main -- ofl
git checkout upstream/main -- ufl

find apache -type f ! \( -name "LICENCE.txt" -o -name "LICENSE.txt" -o -name "OFL.txt" -o -name "UFL.txt" \) -delete
find ufl -type f ! \( -name "LICENCE.txt" -o -name "LICENSE.txt" -o -name "OFL.txt" -o -name "UFL.txt" \) -delete
find ofl -type f ! \( -name "LICENCE.txt" -o -name "LICENSE.txt" -o -name "OFL.txt" -o -name "UFL.txt" \) -delete

rm -r webfonts/css/*
./open-webfonts 9999

# Github will refuse files larger than 100MB happens for one file at the time of writing this
find webfonts/css -type f -size +100M -delete

git add webfonts
git add apache
git add ofl
git add ufl

git commit -am "Update $(date '+%Y-%m-%d--%H-%M-%S')"
git push
