#!/bin/bash

git fetch upstream
git checkout upstream/main -- apache
git checkout upstream/main -- ofl
git checkout upstream/main -- ufl

find apache -type f ! \( -name "LICENCE.txt" -o -name "LICENSE.txt" -o -name "OFL.txt" -o -name "UFL.txt" \) -delete
find ufl -type f ! \( -name "LICENCE.txt" -o -name "LICENSE.txt" -o -name "OFL.txt" -o -name "UFL.txt" \) -delete
find ofl -type f ! \( -name "LICENCE.txt" -o -name "LICENSE.txt" -o -name "OFL.txt" -o -name "UFL.txt" \) -delete

./open-webfonts 9999

git add -A
git commit -am "Update $(date '+%Y-%m-%d--%H-%M-%S')"
git push
